Feature/#27 release and publish
Avaiga/taipy-core pull request #153
Opened 2022-04-11 07:41 UTC by florian-vuillemot

https://app.zenhub.com/workspaces/taipy-613ef328affde6000ff77fb3/issues/avaiga/taipy/27

2022-04-12 08:43 UTC, jrobinAV requested changes

2022-04-12 08:43 UTC, jrobinAV commented on .github/workflows/release.yml
> +      - name: Ensure tag is and package version are equals
```suggestion
      - name: Ensure tag and package version are equals
```
```suggestion
      - name: Ensure tag is and package version are equals
```

2022-04-12 08:43 UTC, jrobinAV commented on .github/workflows/release.yml
>        - 'release/**'
I would change this. 
I believe we don't want to release and publish each time we push on a release/* branch.
I believe it is more convenient to manually trigger the release and publish action.

So that we can create a release branch, share it with others, eventually add new fixes/features, review it, etc. Then, when we are happy about the version, we can release, tag, and publish it.

What do you think? @FabienLelaquais @florian-vuillemot

2022-04-12 08:43 UTC, jrobinAV commented on .github/workflows/release.yml
>        - 'release/**'
I would change this. 
I believe we don't want to release and publish each time we push on a release/* branch.
I believe it is more convenient to manually trigger the release and publish action.

So that we can create a release branch, share it with others, eventually add new fixes/features, review it, etc. Then, when we are happy about the version, we can release, tag, and publish it.

What do you think? @FabienLelaquais @florian-vuillemot

2022-04-13 09:30 UTC, FabienLelaquais commented on .github/workflows/release.yml
>        - 'release/**'
I completely agree with that!

Generating a release on each push of a release branch is fine for me.
But publishing should be a delicate and rare decision. Manual then.

2022-04-13 10:18 UTC, jrobinAV approved these changes, later dismissed

2022-04-14 17:42 UTC, merged

2022-04-15 09:22 UTC, FabienLelaquais reviewed
Nickel

2022-04-15 09:22 UTC, FabienLelaquais commented on .github/workflows/release.yml
> +      - name: Ensure package version is well set
is well set -> is properly set
or
is correct