Feature/#701 - DataNode._get custom properties() API
Avaiga/taipy-core pull request #720
Opened 2023-08-07 11:45 UTC by trgiangdo

https://github.com/Avaiga/taipy-core/issues/701

2023-08-09 07:19 UTC, jrobinAV requested changes
Hello, 
That's not the requirement of ticket #701.

The purpose is to return all properties provided by the end user, without the ones created by Taipy. The list of properties to remove is available [here](https://docs.google.com/document/d/1L5_OPxiAZX9ZU9d6yomMzDZV-Bpv6bA-SW_GRC7n8Do/edit#heading=h.rjc1l3svrrf1).

### Properties to remove: 
**For csv:** exposed_type, path, default_path, default_data, has_header
**For Excel:** exposed_type, path, default_path, default_data, has_header, sheet_name
**For Generic:** read_fct, read_fct_args, write_fct, write_fct_args
**For In Memory:** default_data
**For JSON:** path, default_path, default_data, encoder, decoder
**For Mongo:** custom_document, db_name, collection_name, db_extra_args, db_host, db_port, db_username ,db_password
**For Parquet:** exposed_type, path, default_path, default_data, engine, compression, read_kwargs, write_kwargs
**For Pickle:** path, default_path, default_data, is_generated
**For SQL:** read_query, write_query_builder, exposed_type, db_engine, db_username, db_password, db_name, db_host, db_port, db_driver, db_extra_args, sqlite_folder_path, sqlite_file_extension
**For sql_table:** table_name, db_engine, exposed_type, db_username, db_password, db_name, db_host, db_port, db_driver, db_extra_args, sqlite_folder_path, sqlite_file_extension

2023-08-09 10:20 UTC, trgiangdo commented
Sorry I misunderstood the ticket since there is a `*list_of_properties_to_keep` parameter.

So the `DataNode._get_custom_properties()` will not accept any parameter at all, right?

2023-08-11 15:56 UTC, jrobinAV submitted a review, later dismissed
minor suggestion on the name

2023-08-11 15:56 UTC, jrobinAV commented on src/taipy/core/data/data_node.py
> +    def _get_custom_properties(self) -> Dict[str, Any]:
I am changing my mind, but what about renaming custom properties to user properties `_get_user_properties`?

2023-08-11 15:56 UTC, jrobinAV commented on src/taipy/core/data/data_node.py
> +        """Get custom properties of the data node except from the ones created by TAIPY."""
```suggestion
        """ Get user properties."""
```

2023-08-11 15:58 UTC, trgiangdo commented on src/taipy/core/data/data_node.py
> +    def _get_custom_properties(self) -> Dict[str, Any]:
It's an internal API for now, so why not 😂

2023-08-11 15:59 UTC, trgiangdo commented on src/taipy/core/data/data_node.py
> +    def _get_custom_properties(self) -> Dict[str, Any]:
```suggestion
    def _get_user_properties(self) -> Dict[str, Any]:
```

2023-08-11 16:07 UTC, jrobinAV approved these changes

2023-08-11 16:09 UTC, merged